//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Covoiturage
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Trajet
    {
        public string Id_Trajet { get; set; }

        [Required]
        [Display(Name = "Lieu de départ")]
        public string Lieu_Depart { get; set; }

        [Required]
        [Display(Name = "Lieu d'arrivée")]
        public string Lieu_Arrivee { get; set; }

        [Required]
        [Display(Name = "Date de départ")]
        public System.DateTime Date_Depart { get; set; }

        [Required]
        [Display(Name = "Heure de départ")]
        public System.TimeSpan Heure_Depart { get; set; }

        [Required]
        [Display(Name = "Nombre de places disponibles")]
        public int Nbr_Places_Dispo { get; set; }

        public string Id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
